remote_theme: just-the-docs/just-the-docs
title: Web-App 'Jobfolio'
description: Projektarbeit von Florian Eppe, Khanh Linh Pham und Victoria-Kim Bui für die Veranstaltung Wi-Inf-M09
mermaid:
  version: "9.4.3" # Pick version from https://cdn.jsdelivr.net/npm/mermaid/
callouts:
  tip:
    title: 🤍 Tip
    color: purple
  info:
    title: ℹ️ Info
    color: blue
  attention:
    title: ❕ Attention
    color: yellow
sidebar:
  - title: Value Proposition
    url: /docs/value-proposition/
  - title: App Structure
    url: /docs/app-structure/
  - title: App Behavior
    url: /docs/app-behavior/
  - title: Data Model
    url: /docs/data-model/
  - title: Design Desicions
    url: /docs/design-desicions/
  - title: User Evaluation
    url: /docs/user-evaluation/
  - title: Goals Archieved & Missed
    url: /docs/goals-archieved-missed/
  - title: Possibile Improvements
    url: /docs/possibile-improvements/
  - title: Peer Review
    url: /docs/peer-review/

